settings:
  title: 'Status Page (Under construction)'
  url: 'https://status.foxomy.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: 'You write cdode. They handle the rest.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: www-cloudflare-com
    name: www.cloudflare.com
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.cloudflare.com'
    method: GET
    expectStatus: 200

  - id: blog-cloudflare-comtest
    name: The Cloudflare Blogtest
    url: 'https://blog.cloudflare.com/'
    method: PING
    expectStatus: 200
    
  - id: test
    name: test1s
    url: '199.26.86.175'
    method: PING
    expectStatus: 200

- id: blog-cloudflare-comtest3
    name: The Cloudflare Blogtest3
    url: 'https://blog.cloudflare.com/'
    method: PING
    expectStatus: 200
    
